### ISSUE TITLE
SYMPOSIUM EPIC

### ISSUE THREAD

**Issue by georgeutsin** [georgeutsin/tagbull#1]
Let's group months of work at a time into one issue, to avoid making the issues pane too noisy with feature requests. New issues should probably be high-pri bugs, or tasks that require conversation.

New to rails? give this a read http://apionrails.icalialabs.com/book/chapter_two
New to react? give this a read https://reactjs.org/docs/hello-world.html
Need a reminder of what to build? look at this disaster (in Chrome) https://storage.googleapis.com/openimages/web/visualizer/index.html?set=train&type=segmentation&r=false&c=%2Fm%2F01fb_0

Anyway, some work that we should do off the top of my head, feel free to extend the list:

### Starter Tasks
 - [x] (george) Add a hook to the github repo for testing/CI (and figure out how rails works)
 - [x] Define the donuts/bagels dataset and update the schema
   - [x] (dmediati) Define the classification task for this dataset (eg: occlusion? groups?)
See: https://docs.google.com/document/d/1akk6CW8mkSxx9StJBBCXXFwm8miDSB_v1Eu_o8ge-W8/edit
    - [x] (mdsouza) add batch endpoint for bagels & donuts task (Dichotomy task, which creates a Locator task)
 - [x] (mdsouza) front end: add a help screen under the '?' button
   ~(kpeng and mdsouza) Fixtures: adding local data to rails so there's always something to see~
- [x] (kpeng) Research integration with existing ad networks 

### Tasks
- [x] (kpengu) Create a Locater activity - tap all of the objects in the image for approx location + count
- [x] (george) frontend: create the location target canvas util - displays location of a tap, for the bounding box activity

- [x] (george) Create a Discrete Attribute activity with multi-button, configurable question, number of buttons and button labels 
- [x] (george) backend: add a locator task and sample model, update endpoints
- [x] (george) backend: add a discrete attribute task and sample model, update endpoints
- [x] (george) backend: add a locator sample tag generator
- [x] (george) backend: add a discrete attribute tag generator
- [x] (george) frontend: add visualization for dichotomy task/reuse existing canvases for visualization
- [x] (george) backend: have the generators create new tasks on success (if parent_id on a the task is set, go into that parent's state machine to determine the next task to create)
- [x] (mdsouza) backend: add script to hit the tasks endpoint to generate the bagels/donuts dichotomy tasks
- [x] (david) frontend: add loading spinner to base canvas while image is loading
- [x] (kev) frontend: add timed "no {category} button" next to reset in locator activity
- [x] (george) backend: fix activity ordering to prioritize furthest progressed, THEN oldest (idea: add level field to task, increment by 1 in the top level state machine)
- [x] (david) frontend: reward player if no tasks are available
- [x] (george) frontend: add timeout to all tasks, and change message to "Wow that was fast! Take a moment to review your submission to be extra sure :)"
- [x] (george) backend+frontend: pause/resume projects
- [x] (george) frontend: update good job component to say "you're finished! tap anywhere to claim your reward" and add confetti lol
- [x] (george) frontend: add internal tooling support for the different kinds of samples
- [x] (george) frontend: fix bounding box creation on the edge of the canvas (when box edge is dragged off the edge of the canvas, snap it to the edge)
- [x] (mdsouza) backend: compress images for faster loading
- [x] (george) frontend: increment progress on bounding box
- [x] (george) frontend: bounding box has to be surrounding the marker for it to be correct
- [x] (kev) frontend+backend: if bounding box covers all locator points, then reject
- [x] (george) frontend: add ability to edit previous edges in bb creation activity
- [x] (george) frontend: fix depiction activity wording + image
- [x] (mdsouza) backend: automate trunacted task to be false if bb isn't near the edge
- [x] (george) frontend: fix occluded task wording (specify that it includes the category)
- [x] (george) backend: fix internal tooling (use base task id instead of specific task id in `tag_for`)
- [x] (george) backend: fix locator to bring the threshold up and not lose points that are kinda far
- [x] (mdsouza && george) backend: tags endpoint takes way too long to load - debug perf or consider paging?
- [x] label entire dataset ourselves
- [x] (george) frontend: create endpoint that takes two projects, pulls tags, and diffs them
- [ ] backend: figure out which tasks are problematic and increase redundancy requirement in generators
- [ ] fullstack: build out actor based tooling (input actor id, show all samples for that actor)
- [ ] backend: actor trust profiles (this probably deserves its own issue)
- [x] (kev && george) frontend: alert when box is too tight around target (in case its an honest mistake)
- [x] (kev) frontend: autogenerate turk id for use on our end. Maintain turk id for payments only.
- [x] (george) frontend: fix bb activity wording
- [ ] fullstack: aggregate project stats and display them on project page (number of samples broken down by type, number of tags broken down by type, average time per sample, number of image?)
- [ ] fullstack: aggregate diff stats in diff view (number of extra bound boxes, missing boxes, correct boxes, # of same & diff results for each discrete attribute)

### Wishlist
- [ ] UX fixes
  - [x] when adjusting edges, and left/right or top/bottom are swapped, still highlight/gray out image regions correctly.
  - [ ] [BoundingBox, Locator] add a maginifying glass above the touch to show where the pointer is
  - [ ] add a pinch to zoom feature to the base canvas
  - [x] (george) format the help button component
  - [x] add FAQ + animations/example samples
- [x] (george) backend: a better points list comparison function
- [ ] backend+frontend: integrate existing open images dataset for comparison - need a new table?
- [ ] frontend: overhaul css to split by file
- [ ] backend: investigate NOT using a sql state machine on the basic tasks
- [ ] backend: investigate handling random generator failure: it happens due to code errors, but as of rn theres no way to recover :(
- [ ] New actor onboarding
  - [x] (mdsouza) backend: new actor flag
  - [ ] **frontend: onboarding flow (with predefined question with answers, animations)**
- [ ] backend: remove timestamps on actables
- [ ] backend: monitor how many people skip, or modify the consensus on the backend when there are no objects in scene
- [ ] frontend: [bug] editing a bb tap activity to an incorrect bounding box causes an error message, but still allows the erroneous box to be submitted
