### ISSUE TITLE
LAUNCH EPIC

### ISSUE THREAD

**Issue by georgeutsin** [georgeutsin/tagbull#107]
## CORRECTNESS
- [x] parametrize the redundancy factor (from pairwise to n-wise)
- [x] create locator only project
  - [x] add locator project creation endpoint
  - [x] add "too many items" option

## PRODUCT
- [x] change progress to be based on number of images, not tasks
- [x] add actor view (feeds into correctness:trust profiles)
  - [x] `/projects/:id/` - actors tab next to tags
  - [x] `/projects/:id/actors/:id`
  - [x] `/actors` - filtered to projects the vc owns
  - [x] `/actors/:id` - filtered to projects the vc owns
- [x] add authentication
- [x] add delete project (backend + frontend)
- [x] add view activities button
- [x] add bb, da project creation
- [x] add locator, da tag previews
- [x] export tags as csv button
- [x] (re)add create project

## TECH DEBT
- [x] frontend: split css by file

## OPS
- [x] migrate to heroku

## ICEBOX
- add actor trust profiles
  - [x] update `is_active` attribute on sample
  - add helper methods for actor utils (`get_trust`)
  - use trust metric during sample generation

**Comment by georgeutsin** [comment]
Closing this issue because all of the MVP features are done
